{% set name = "hankel" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b74f8b776967976c1a9902d4780d33e4907509cfcdd17feec75b4416fba84039

build:
  noarch: python
  number: 0
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=45
    - setuptools_scm >=3.4
  run:
    - python >=3.5
    - scipy >=0.16.1
    - mpmath >=1.0.0
    - numpy >=1.9.3

test:
  imports:
    - hankel

about:
  home: https://github.com/steven-murray/hankel
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Hankel Transformations using method of Ogata 2005
  description: |
    Hankel transforms and integrals are commonplace in any area in which Fourier Transforms are required over fields that are radially symmetric.
    They involve integrating an arbitrary function multiplied by a Bessel function of arbitrary order (of the first kind).
    Typical integration schemes often fail because of the highly oscillatory nature of the transform.
    Ogata's quadrature method used in this package provides a fast and accurate way of performing the integration based on locating the zeros of the Bessel function.
  doc_url: https://hankel.readthedocs.io/
  dev_url: https://github.com/steven-murray/hankel

extra:
  recipe-maintainers:
    - MuellerSeb
    - steven-murray
